[workspace]
members = [
    "zallet",
]
resolver = "2"

[workspace.package]
authors = [
    "Jack Grigg <jack@electriccoin.co>",
    "Kris Nuttycombe <kris@electriccoin.co>",
]
edition = "2021"
rust-version = "1.82"
repository = "https://github.com/zcash/wallet"
license = "MIT OR Apache-2.0"
categories = ["cryptography::cryptocurrencies"]

[workspace.dependencies]
# Async
futures = "0.3"
tokio = "1"

# Localization
i18n-embed = { version = "0.15", features = ["fluent-system"] }
i18n-embed-fl = "0.9"
rust-embed = "8"

# Parsing and serialization
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"

# Randomness
rand = "0.8"

# CLI
abscissa_core = "0.8"
abscissa_tokio = "0.8"
clap = { version = "4.5", features = ["derive"] }

# RPC
http-body-util = "0.1"
hyper = "1"
jsonrpsee = "0.24"
tower = "0.4"
