[workspace]
members = [
    "zallet",
]
resolver = "2"

[workspace.package]
authors = [
    "Jack Grigg <jack@electriccoin.co>",
    "Kris Nuttycombe <kris@electriccoin.co>",
]
edition = "2021"
rust-version = "1.82"
repository = "https://github.com/zcash/wallet"
license = "MIT OR Apache-2.0"
categories = ["cryptography::cryptocurrencies"]

[workspace.dependencies]
# Async
async-trait = "0.1"
futures = "0.3"
tokio = "1"

# Filesystem
home = "0.5"
known-folders = "1"
xdg = "2.5"

# Localization
i18n-embed = { version = "0.15", features = ["fluent-system"] }
i18n-embed-fl = "0.9"
rust-embed = "8"

# Parsing and serialization
hex = "0.4"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
toml = "0.8"

# Randomness
rand = "0.8"

# CLI
abscissa_core = "0.8"
abscissa_tokio = "0.8"
clap = { version = "4.5", features = ["derive"] }

# RPC
http-body-util = "0.1"
hyper = "1"
jsonrpsee = "0.24"
tower = "0.4"

# Zcash consensus
zcash_protocol = "0.5"

# Zcash payment protocols
orchard = "0.11"
sapling = { package = "sapling-crypto", version = "0.5" }
transparent = { package = "zcash_transparent", version = "0.2" }
zcash_primitives = "0.22"

# Zcash wallet
deadpool = "0.12"
deadpool-sqlite = "0.9"
deadpool-sync = "0.1"
rusqlite = "0.32"
schemerz = "0.2"
secrecy = "0.8"
shardtree = "0.6"
zcash_client_backend = "0.17"
zcash_client_sqlite = "0.15"
zip32 = "0.2"

# lightwalletd (temporary)
tonic = "0.12"

[patch.crates-io]
transparent = { package = "zcash_transparent", git = "https://github.com/zcash/librustzcash.git", rev = "4a8cd251ef5cc7779d23ee02d8c60feb56520eaa" }
zcash_client_backend = { git = "https://github.com/zcash/librustzcash.git", rev = "4a8cd251ef5cc7779d23ee02d8c60feb56520eaa" }
zcash_client_sqlite = { git = "https://github.com/zcash/librustzcash.git", rev = "4a8cd251ef5cc7779d23ee02d8c60feb56520eaa" }
zcash_primitives = { git = "https://github.com/zcash/librustzcash.git", rev = "4a8cd251ef5cc7779d23ee02d8c60feb56520eaa" }
zcash_protocol = { git = "https://github.com/zcash/librustzcash.git", rev = "4a8cd251ef5cc7779d23ee02d8c60feb56520eaa" }
