[workspace]
members = [
    "zallet",
]
resolver = "2"

[workspace.package]
authors = [
    "Jack Grigg <jack@electriccoin.co>",
    "Kris Nuttycombe <kris@electriccoin.co>",
]
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/zcash/wallet"
license = "MIT OR Apache-2.0"
categories = ["cryptography::cryptocurrencies"]

[workspace.dependencies]
# Async
async-trait = "0.1"
futures = "0.3"
tokio = "1"

# Filesystem
home = "0.5"
known-folders = "1"
xdg = "2.5"

# Key storage
age = { version = "0.11", features = ["armor", "cli-common", "plugin"] }
bip0039 = "0.12"

# Localization
i18n-embed = { version = "0.15", features = ["fluent-system"] }
i18n-embed-fl = "0.9"
rust-embed = "8"

# Parsing and serialization
hex = "0.4"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
toml = "0.8"
zcash_address = "0.7"

# Randomness
rand = "0.8"

# CLI
abscissa_core = "0.8"
abscissa_tokio = "0.8"
clap = { version = "4.5", features = ["derive"] }

# RPC
http-body-util = "0.1"
hyper = "1"
jsonrpsee = "0.24"
tower = "0.4"

# Zcash consensus
zcash_protocol = "0.5"

# Zcash payment protocols
orchard = "0.11"
sapling = { package = "sapling-crypto", version = "0.5" }
transparent = { package = "zcash_transparent", version = "0.2" }
zcash_keys = "0.8"
zcash_primitives = "0.22"

# Zcash chain state
zaino-fetch = { git = "https://github.com/zingolabs/zaino.git", rev = "2b2ebb4725d771724c724587e2dfe44af7b46377" }
zaino-proto = { git = "https://github.com/zingolabs/zaino.git", rev = "2b2ebb4725d771724c724587e2dfe44af7b46377" }
zaino-state = { git = "https://github.com/zingolabs/zaino.git", rev = "2b2ebb4725d771724c724587e2dfe44af7b46377" }
# - We do not use branch dependencies in general because they are brittle, but are forced
#   to do so here because Zaino does.
zebra-chain = { git = "https://github.com/ZcashFoundation/zebra.git", branch = "main" }
zebra-rpc = { git = "https://github.com/ZcashFoundation/zebra.git", branch = "main" }
zebra-state = { git = "https://github.com/ZcashFoundation/zebra.git", branch = "main" }

# Zcash wallet
deadpool = "0.12"
deadpool-sqlite = "0.9"
deadpool-sync = "0.1"
rusqlite = { version = "0.32", features = ["time"] }
schemerz = "0.2"
schemerz-rusqlite = "0.320.0"
secrecy = "0.8"
shardtree = "0.6"
time = "0.3"
uuid = "1"
zcash_client_backend = "0.18"
zcash_client_sqlite = "0.16"
zip32 = "0.2"

# lightwalletd (temporary)
tonic = "0.13"

[patch.crates-io]
age = { git = "https://github.com/str4d/rage.git", rev = "84dc1e9f641994388f107ceebdbaa00126e30e16" }
equihash = { git = "https://github.com/zcash/librustzcash.git", rev = "0489ed87940fc729963edb3cc5d59985b52b3326" }
transparent = { package = "zcash_transparent", git = "https://github.com/zcash/librustzcash.git", rev = "0489ed87940fc729963edb3cc5d59985b52b3326" }
zcash_address = { git = "https://github.com/zcash/librustzcash.git", rev = "0489ed87940fc729963edb3cc5d59985b52b3326" }
zcash_client_backend = { git = "https://github.com/zcash/librustzcash.git", rev = "0489ed87940fc729963edb3cc5d59985b52b3326" }
zcash_client_sqlite = { git = "https://github.com/zcash/librustzcash.git", rev = "0489ed87940fc729963edb3cc5d59985b52b3326" }
zcash_encoding = { git = "https://github.com/zcash/librustzcash.git", rev = "0489ed87940fc729963edb3cc5d59985b52b3326" }
zcash_history = { git = "https://github.com/zcash/librustzcash.git", rev = "0489ed87940fc729963edb3cc5d59985b52b3326" }
zcash_keys = { git = "https://github.com/zcash/librustzcash.git", rev = "0489ed87940fc729963edb3cc5d59985b52b3326" }
zcash_primitives = { git = "https://github.com/zcash/librustzcash.git", rev = "0489ed87940fc729963edb3cc5d59985b52b3326" }
zcash_proofs = { git = "https://github.com/zcash/librustzcash.git", rev = "0489ed87940fc729963edb3cc5d59985b52b3326" }
zcash_protocol = { git = "https://github.com/zcash/librustzcash.git", rev = "0489ed87940fc729963edb3cc5d59985b52b3326" }
