[workspace]
members = [
    "zallet",
]
resolver = "2"

[workspace.package]
authors = [
    "Jack Grigg <jack@electriccoin.co>",
    "Kris Nuttycombe <kris@electriccoin.co>",
]
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/zcash/wallet"
license = "MIT OR Apache-2.0"
categories = ["cryptography::cryptocurrencies"]

[workspace.dependencies]
# Async
async-trait = "0.1"
futures = "0.3"
tokio = "1"

# Build script
shadow-rs = { version = "1.2", default-features = false }

# Documentation
documented = "0.9"
phf = { version = "0.11", features = ["macros"] }

# Filesystem
fmutex = "0.3"
home = "0.5"
known-folders = "1"
xdg = "2.5"

# Key storage
age = { version = "0.11", features = ["armor", "cli-common", "plugin"] }
bip0039 = "0.12"

# Localization
i18n-embed = { version = "0.16", features = ["fluent-system"] }
i18n-embed-fl = "0.10"
rust-embed = "8"

# Parsing and serialization
hex = "0.4"
serde = { version = "1", features = ["serde_derive"] }
serde_json = { version = "1", features = ["arbitrary_precision", "raw_value"] }
toml = "0.8"
zcash_address = "0.9"

# Randomness
rand = "0.8"

# CLI
abscissa_core = "0.8"
abscissa_tokio = "0.8"
clap = { version = "4.5", features = ["derive"] }
rpassword = "7"

# RPC
http-body-util = "0.1"
hyper = "1"
jsonrpsee = "0.24"
jsonrpsee-http-client = { version = "0.24", default-features = false }
nix = "0.29" # `stop` RPC method
rust_decimal = { version = "1.37", default-features = false, features = [
    "serde-arbitrary-precision",
    "serde-float",
] }
schemars = "0.9"
tower = "0.4"

# Tracing
console-subscriber = "0.4"
tracing = { version = "0.1", features = ["attributes"] }
tracing-log = "0.2"
tracing-subscriber = "0.3"

# Zcash consensus
zcash_protocol = "0.6"

# Zcash payment protocols
orchard = "0.11"
sapling = { package = "sapling-crypto", version = "0.5" }
transparent = { package = "zcash_transparent", version = "0.4" }
zcash_keys = { version = "0.10", features = ["transparent-inputs", "sapling", "orchard", "transparent-key-encoding"] }
zcash_primitives = "0.24"
zcash_proofs = "0.24"
secp256k1 = "0.29"

# Zcash chain state
zaino-fetch = "0.1"
zaino-proto = "0.1"
zaino-state = "0.1"
zebra-chain = "2.0"
zebra-rpc = "2.0.1"
zebra-state = "2.0"

# Zcash wallet
deadpool = "0.12"
deadpool-sqlite = "0.9"
deadpool-sync = "0.1"
incrementalmerkletree = "0.8.2"
rusqlite = { version = "0.32", features = ["time"] }
schemerz = "0.2"
schemerz-rusqlite = "0.320.0"
secrecy = "0.8"
shardtree = "0.6"
time = "0.3"
uuid = "1"
zcash_client_backend = "0.19"
zcash_client_sqlite = "0.17"
zcash_note_encryption = "0.4"
zip32 = "0.2"
bip32 = "0.2"

# Zcashd wallet migration
zewif = { version = "0.1" }
zewif-zcashd = { version = "0.1" }
anyhow = "1.0"

# lightwalletd (temporary)
tonic = "0.13"

[patch.crates-io]
age = { git = "https://github.com/str4d/rage.git", rev = "92f437bc2a061312fa6633bb70c91eef91142fd4" }

abscissa_core = { git = "https://github.com/iqlusioninc/abscissa.git", rev = "fdb60678fb3a883decf63d6d3ebc512abd20406f" }
abscissa_tokio = { git = "https://github.com/iqlusioninc/abscissa.git", rev = "fdb60678fb3a883decf63d6d3ebc512abd20406f" }

equihash = { git = "https://github.com/zcash/librustzcash.git", rev = "cab5fe36ca689c43ab48de8eb528d5dd60adbb75" }
transparent = { package = "zcash_transparent", git = "https://github.com/zcash/librustzcash.git", rev = "cab5fe36ca689c43ab48de8eb528d5dd60adbb75" }
zcash_address = { git = "https://github.com/zcash/librustzcash.git", rev = "cab5fe36ca689c43ab48de8eb528d5dd60adbb75" }
zcash_client_backend = { git = "https://github.com/zcash/librustzcash.git", rev = "cab5fe36ca689c43ab48de8eb528d5dd60adbb75" }
zcash_client_sqlite = { git = "https://github.com/zcash/librustzcash.git", rev = "cab5fe36ca689c43ab48de8eb528d5dd60adbb75" }
zcash_encoding = { git = "https://github.com/zcash/librustzcash.git", rev = "cab5fe36ca689c43ab48de8eb528d5dd60adbb75" }
zcash_history = { git = "https://github.com/zcash/librustzcash.git", rev = "cab5fe36ca689c43ab48de8eb528d5dd60adbb75" }
zcash_keys = { git = "https://github.com/zcash/librustzcash.git", rev = "cab5fe36ca689c43ab48de8eb528d5dd60adbb75" }
zcash_primitives = { git = "https://github.com/zcash/librustzcash.git", rev = "cab5fe36ca689c43ab48de8eb528d5dd60adbb75" }
zcash_proofs = { git = "https://github.com/zcash/librustzcash.git", rev = "cab5fe36ca689c43ab48de8eb528d5dd60adbb75" }
zcash_protocol = { git = "https://github.com/zcash/librustzcash.git", rev = "cab5fe36ca689c43ab48de8eb528d5dd60adbb75" }

zewif = { git = "https://github.com/zcash/zewif.git", rev = "f84f80612813ba00a0a8a9a5f060bd217fa981cc" }
zewif-zcashd = { git = "https://github.com/zcash/zewif-zcashd.git", rev = "02a98d6236e24819904e084180da9ba0f5c9b5d0" }

zaino-fetch = { git = "https://github.com/Electric-Coin-Company/zaino.git", rev = "1004733f3303b1c48b6df6db610c54401554683c" }
zaino-proto = { git = "https://github.com/Electric-Coin-Company/zaino.git", rev = "1004733f3303b1c48b6df6db610c54401554683c" }
zaino-state = { git = "https://github.com/Electric-Coin-Company/zaino.git", rev = "1004733f3303b1c48b6df6db610c54401554683c" }

zip32 = { git = "https://github.com/zcash/zip32.git", rev = "3fd1ab9e1cb943edde58579cd5c65095494810cb" }
