# Configuration file for cargo-deny

[graph]
targets = [
    { triple = "aarch64-apple-darwin" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-gnu" },
    { triple = "x86_64-unknown-freebsd" },
    { triple = "x86_64-unknown-linux-gnu" },
]
all-features = true
exclude-dev = true

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
]
exceptions = [
    { name = "arrayref", allow = ["BSD-2-Clause"] },
    { name = "curve25519-dalek", allow = ["BSD-3-Clause"] },
    { name = "matchit", allow = ["BSD-3-Clause"] },
    { name = "rustls-webpki", allow = ["ISC"] },
    { name = "secp256k1", allow = ["CC0-1.0"] },
    { name = "secp256k1-sys", allow = ["CC0-1.0"] },
    { name = "subtle", allow = ["BSD-3-Clause"] },
    { name = "tinystr", allow = ["Unicode-3.0"] },
    { name = "unicode-ident", allow = ["Unicode-3.0"] },
    { name = "untrusted", allow = ["ISC"] },
    { name = "webpki-roots", allow = ["MPL-2.0"] },
    { name = "x25519-dalek", allow = ["BSD-3-Clause"] },
]
