[package]
name = "zallet"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A prototype wallet. Don't rely on this for privacy or with significant funds yet!"
license.workspace = true
categories.workspace = true

[dependencies]
abscissa_core.workspace = true
abscissa_tokio.workspace = true
clap = { workspace = true, features = ["string", "unstable-styles"] }
futures.workspace = true
home.workspace = true
http-body-util.workspace = true
hyper.workspace = true
i18n-embed = { workspace = true, features = ["desktop-requester"] }
i18n-embed-fl.workspace = true
jsonrpsee = { workspace = true, features = ["macros", "server"] }
rand.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = [
    "fs",
    "io-util",
    "macros",
    "rt-multi-thread",
] }
toml.workspace = true
tower = { workspace = true, features = ["timeout"] }

[dev-dependencies]
abscissa_core = { workspace = true, features = ["testing"] }
once_cell = "1.2"
