name: Audits

on:
  pull_request:
  push:
    branches: main

permissions:
  contents: read

jobs:
  cargo-vet:
    name: Vet Rust dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
      - run: rustup override set "${TOOLCHAIN}"
        env:
          TOOLCHAIN: ${{steps.toolchain.outputs.name}}
      - run: cargo install cargo-vet --version ~0.10
      - run: cargo vet --locked

  required-audits:
    name: Required audits have passed
    needs:
      - cargo-vet
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine whether all required-pass steps succeeded
        run: |
          echo "${NEEDS}" | jq -e '[ .[] | .result == "success" ] | all'
        env:
          NEEDS: ${{ toJSON(needs) }}
