name: Build and Push Docker Image to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions: {}

jobs:
  set_env:
    name: Create version tag
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.version_step.outputs.tags }}
      zallet_version: ${{ steps.version_step.outputs.zallet_version }}
    steps:
    - id: version_step
      run:  |
        if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-rc-[0-9]+)?$ ]]; then
          safe_ref_name="${{ github.ref_name }}"
          echo "tags=latest,${safe_ref_name},${{ github.sha }}" >> $GITHUB_OUTPUT
          zallet_version=$(echo "$safe_ref_name" | sed 's/^v//')
          echo "zallet_version=$zallet_version" >> $GITHUB_OUTPUT
        else
          echo "Invalid ref_name format: ${{ github.ref_name }}" >&2
          exit 1
        fi

  build_push:
    uses: zcash/.github/.github/workflows/build-and-push-docker-hub.yaml@main
    needs: set_env
    with:
      image_name: zallet
      image_tags: ${{ needs.set_env.outputs.tags }}
      dockerfile: Dockerfile
      context: .
      build-args: ""
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      dockerhub_registry: ${{ secrets.DOCKERHUB_REGISTRY }}
